-- CineAssemble production schema for MySQL 8.0+
-- All customer-owned records carry user_id and are accessed through tenant-scoped repositories.

CREATE TABLE IF NOT EXISTS plans (
  id CHAR(36) NOT NULL,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(80) NOT NULL,
  price_monthly_cents INT UNSIGNED NOT NULL DEFAULT 0,
  monthly_credits INT UNSIGNED NOT NULL DEFAULT 0,
  max_video_minutes TINYINT UNSIGNED NOT NULL DEFAULT 5,
  max_concurrent_jobs TINYINT UNSIGNED NOT NULL DEFAULT 1,
  watermark_required BOOLEAN NOT NULL DEFAULT TRUE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  entitlements JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_plans_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO plans (
  id, code, name, price_monthly_cents, monthly_credits,
  max_video_minutes, max_concurrent_jobs, watermark_required, entitlements
) VALUES
  ('00000000-0000-4000-8000-000000000001', 'trial', 'Free Trial', 0, 2, 1, 1, TRUE,
    JSON_OBJECT('quality_tiers', JSON_ARRAY('budget'), 'public_sharing', TRUE)),
  ('00000000-0000-4000-8000-000000000009', 'starter', 'Starter', 900, 20, 3, 1, FALSE,
    JSON_OBJECT('quality_tiers', JSON_ARRAY('budget', 'standard'), 'public_sharing', TRUE)),
  ('00000000-0000-4000-8000-000000000029', 'creator', 'Creator', 2900, 80, 5, 2, FALSE,
    JSON_OBJECT('quality_tiers', JSON_ARRAY('budget', 'standard', 'premium'), 'brand_kits', TRUE, 'public_sharing', TRUE)),
  ('00000000-0000-4000-8000-000000000079', 'agency', 'Agency', 7900, 250, 5, 4, FALSE,
    JSON_OBJECT('quality_tiers', JSON_ARRAY('budget', 'standard', 'premium'), 'brand_kits', TRUE, 'public_sharing', TRUE, 'priority_queue', TRUE))
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  price_monthly_cents = VALUES(price_monthly_cents),
  monthly_credits = VALUES(monthly_credits),
  max_video_minutes = VALUES(max_video_minutes),
  max_concurrent_jobs = VALUES(max_concurrent_jobs),
  watermark_required = VALUES(watermark_required),
  entitlements = VALUES(entitlements),
  updated_at = CURRENT_TIMESTAMP(3);

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) NOT NULL,
  email VARCHAR(320) NOT NULL,
  email_normalized VARCHAR(320) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  status ENUM('pending_verification', 'active', 'suspended', 'deleted') NOT NULL DEFAULT 'pending_verification',
  plan_id CHAR(36) NOT NULL DEFAULT '00000000-0000-4000-8000-000000000001',
  email_verified_at DATETIME(3) NULL,
  trial_started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  trial_used_at DATETIME(3) NULL,
  last_login_at DATETIME(3) NULL,
  password_changed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email_normalized (email_normalized),
  KEY idx_users_role_status (role, status),
  KEY idx_users_plan (plan_id),
  CONSTRAINT fk_users_plan FOREIGN KEY (plan_id) REFERENCES plans(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sessions (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  csrf_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  user_agent_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  ip_prefix VARBINARY(16) NULL,
  last_seen_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  idle_expires_at DATETIME(3) NOT NULL,
  absolute_expires_at DATETIME(3) NOT NULL,
  revoked_at DATETIME(3) NULL,
  revoke_reason VARCHAR(80) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_sessions_token_hash (token_hash),
  KEY idx_sessions_user_active (user_id, revoked_at, idle_expires_at),
  KEY idx_sessions_expiry (absolute_expires_at),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS auth_tokens (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  purpose ENUM('verify_email', 'reset_password', 'change_email') NOT NULL,
  token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  pending_value VARCHAR(320) NULL,
  expires_at DATETIME(3) NOT NULL,
  consumed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_auth_tokens_hash (token_hash),
  KEY idx_auth_tokens_user_purpose (user_id, purpose, consumed_at, expires_at),
  CONSTRAINT fk_auth_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS subscriptions (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  plan_id CHAR(36) NOT NULL,
  provider ENUM('paypal', 'manual') NOT NULL DEFAULT 'paypal',
  provider_subscription_id VARCHAR(160) NULL,
  provider_payer_id VARCHAR(160) NULL,
  status ENUM('pending', 'active', 'past_due', 'paused', 'cancelled', 'expired') NOT NULL DEFAULT 'pending',
  current_period_start DATETIME(3) NULL,
  current_period_end DATETIME(3) NULL,
  cancelled_at DATETIME(3) NULL,
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_subscriptions_provider_id (provider, provider_subscription_id),
  KEY idx_subscriptions_user_status (user_id, status),
  CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES plans(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS credit_ledger (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  amount INT NOT NULL,
  entry_type ENUM('trial_grant', 'subscription_grant', 'pack_purchase', 'reservation', 'charge', 'refund', 'adjustment', 'referral_reward') NOT NULL,
  reference_type VARCHAR(40) NULL,
  reference_id CHAR(36) NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  description VARCHAR(255) NULL,
  metadata JSON NULL,
  created_by_user_id CHAR(36) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_credit_ledger_idempotency (idempotency_key),
  KEY idx_credit_ledger_user_created (user_id, created_at),
  KEY idx_credit_ledger_reference (reference_type, reference_id),
  CONSTRAINT fk_credit_ledger_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_credit_ledger_actor FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS assets (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  kind ENUM('product_original', 'product_cutout', 'character_reference', 'brand_logo', 'voice_sample', 'background_music', 'scene_image', 'scene_audio', 'scene_clip', 'scene_lipsync', 'final_video', 'thumbnail', 'other') NOT NULL,
  storage_provider ENUM('local', 's3') NOT NULL DEFAULT 'local',
  storage_key VARCHAR(768) NOT NULL,
  original_name VARCHAR(255) NULL,
  mime_type VARCHAR(100) NOT NULL,
  byte_size BIGINT UNSIGNED NOT NULL,
  width INT UNSIGNED NULL,
  height INT UNSIGNED NULL,
  duration_ms BIGINT UNSIGNED NULL,
  sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  visibility ENUM('private', 'share') NOT NULL DEFAULT 'private',
  source_asset_id CHAR(36) NULL,
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_assets_storage_key (storage_key),
  KEY idx_assets_user_kind_created (user_id, kind, created_at),
  KEY idx_assets_sha256 (user_id, sha256),
  CONSTRAINT fk_assets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_assets_source FOREIGN KEY (source_asset_id) REFERENCES assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS products (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  name VARCHAR(140) NOT NULL,
  description TEXT NULL,
  original_asset_id CHAR(36) NOT NULL,
  cutout_asset_id CHAR(36) NULL,
  strict_fidelity BOOLEAN NOT NULL DEFAULT TRUE,
  preservation_notes TEXT NULL,
  product_profile JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_products_user_created (user_id, created_at),
  CONSTRAINT fk_products_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_products_original_asset FOREIGN KEY (original_asset_id) REFERENCES assets(id),
  CONSTRAINT fk_products_cutout_asset FOREIGN KEY (cutout_asset_id) REFERENCES assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS brand_kits (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  name VARCHAR(120) NOT NULL,
  logo_asset_id CHAR(36) NULL,
  primary_color CHAR(7) NOT NULL DEFAULT '#F59E0B',
  secondary_color CHAR(7) NOT NULL DEFAULT '#09090B',
  outro_text VARCHAR(180) NULL,
  caption_style JSON NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_brand_kits_user_default (user_id, is_default),
  CONSTRAINT fk_brand_kits_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_brand_kits_logo FOREIGN KEY (logo_asset_id) REFERENCES assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS character_library (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  name VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  reference_asset_id CHAR(36) NULL,
  voice VARCHAR(40) NULL,
  is_child BOOLEAN NOT NULL DEFAULT FALSE,
  profile JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_character_library_user_created (user_id, created_at),
  CONSTRAINT fk_character_library_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_character_library_asset FOREIGN KEY (reference_asset_id) REFERENCES assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS jobs (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  title VARCHAR(220) NULL,
  prompt TEXT NOT NULL,
  film_type ENUM(
    'cartoon_story',
    'product_promo',
    'realistic_human',
    'social_ad',
    'explainer',
    'cinematic_story',
    'reference_video'
  ) NOT NULL DEFAULT 'cartoon_story',
  language_code VARCHAR(16) NOT NULL DEFAULT 'en',
  aspect_ratio ENUM('16:9', '9:16', '1:1') NOT NULL DEFAULT '16:9',
  target_minutes TINYINT UNSIGNED NOT NULL DEFAULT 3,
  voice VARCHAR(40) NOT NULL DEFAULT 'auto',
  quality_tier ENUM('budget', 'standard', 'premium') NOT NULL DEFAULT 'budget',
  style_preset VARCHAR(180) NOT NULL,
  mode ENUM('narration', 'dialogue') NOT NULL DEFAULT 'narration',
  subtitles BOOLEAN NOT NULL DEFAULT TRUE,
  karaoke_captions BOOLEAN NOT NULL DEFAULT FALSE,
  lipsync BOOLEAN NOT NULL DEFAULT FALSE,
  brand_kit_id CHAR(36) NULL,
  status ENUM('draft', 'queued', 'running', 'done', 'error', 'cancelled') NOT NULL DEFAULT 'draft',
  stage VARCHAR(40) NOT NULL DEFAULT 'draft',
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  script_json JSON NULL,
  resolved_voice VARCHAR(40) NULL,
  final_asset_id CHAR(36) NULL,
  watermark_required BOOLEAN NOT NULL DEFAULT TRUE,
  estimated_cost_usd DECIMAL(10,4) NOT NULL DEFAULT 0,
  actual_cost_usd DECIMAL(10,4) NOT NULL DEFAULT 0,
  estimated_credits INT UNSIGNED NOT NULL DEFAULT 0,
  reserved_credits INT UNSIGNED NOT NULL DEFAULT 0,
  charged_credits INT UNSIGNED NOT NULL DEFAULT 0,
  error_code VARCHAR(80) NULL,
  error_message TEXT NULL,
  retry_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  priority SMALLINT NOT NULL DEFAULT 0,
  queue_available_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  lease_owner VARCHAR(120) NULL,
  lease_expires_at DATETIME(3) NULL,
  heartbeat_at DATETIME(3) NULL,
  cancel_requested_at DATETIME(3) NULL,
  approved_at DATETIME(3) NULL,
  started_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_jobs_user_created (user_id, created_at),
  KEY idx_jobs_user_status (user_id, status, updated_at),
  KEY idx_jobs_queue_claim (status, queue_available_at, priority, lease_expires_at),
  CONSTRAINT fk_jobs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_jobs_brand_kit FOREIGN KEY (brand_kit_id) REFERENCES brand_kits(id) ON DELETE SET NULL,
  CONSTRAINT fk_jobs_final_asset FOREIGN KEY (final_asset_id) REFERENCES assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS scenes (
  id CHAR(36) NOT NULL,
  job_id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  scene_index SMALLINT UNSIGNED NOT NULL,
  revision SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  narration TEXT NOT NULL,
  dialogue_json JSON NULL,
  image_prompt TEXT NOT NULL,
  motion_prompt TEXT NOT NULL,
  audio_duration_ms INT UNSIGNED NULL,
  image_asset_id CHAR(36) NULL,
  audio_asset_id CHAR(36) NULL,
  clip_asset_id CHAR(36) NULL,
  lipsync_asset_id CHAR(36) NULL,
  status ENUM('draft', 'pending', 'rendering', 'ready', 'error') NOT NULL DEFAULT 'draft',
  error_code VARCHAR(80) NULL,
  error_message TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_scenes_job_index (job_id, scene_index),
  KEY idx_scenes_user_job (user_id, job_id),
  CONSTRAINT fk_scenes_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_scenes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_scenes_image FOREIGN KEY (image_asset_id) REFERENCES assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_scenes_audio FOREIGN KEY (audio_asset_id) REFERENCES assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_scenes_clip FOREIGN KEY (clip_asset_id) REFERENCES assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_scenes_lipsync FOREIGN KEY (lipsync_asset_id) REFERENCES assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS job_assets (
  id CHAR(36) NOT NULL,
  job_id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  asset_id CHAR(36) NOT NULL,
  product_id CHAR(36) NULL,
  asset_role ENUM('product', 'character', 'logo', 'voice', 'background', 'music') NOT NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_job_assets_relation (job_id, asset_id, asset_role),
  KEY idx_job_assets_user_job (user_id, job_id),
  CONSTRAINT fk_job_assets_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_assets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_assets_asset FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_assets_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS job_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  scene_id CHAR(36) NULL,
  level ENUM('debug', 'info', 'warning', 'error') NOT NULL DEFAULT 'info',
  event_type VARCHAR(80) NOT NULL,
  message VARCHAR(1000) NOT NULL,
  progress TINYINT UNSIGNED NULL,
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_job_events_job_id (job_id, id),
  KEY idx_job_events_user_created (user_id, created_at),
  CONSTRAINT fk_job_events_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_events_scene FOREIGN KEY (scene_id) REFERENCES scenes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS provider_operations (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  job_id CHAR(36) NOT NULL,
  scene_id CHAR(36) NULL,
  operation_key VARCHAR(190) NOT NULL,
  provider VARCHAR(40) NOT NULL,
  operation_type VARCHAR(60) NOT NULL,
  provider_request_id VARCHAR(190) NULL,
  status ENUM('pending', 'running', 'succeeded', 'failed', 'unknown') NOT NULL DEFAULT 'pending',
  request_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  output_asset_id CHAR(36) NULL,
  cost_usd DECIMAL(10,4) NOT NULL DEFAULT 0,
  attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  started_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_provider_operations_key (operation_key),
  KEY idx_provider_operations_job (job_id, status),
  CONSTRAINT fk_provider_operations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_provider_operations_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_provider_operations_scene FOREIGN KEY (scene_id) REFERENCES scenes(id) ON DELETE SET NULL,
  CONSTRAINT fk_provider_operations_asset FOREIGN KEY (output_asset_id) REFERENCES assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS share_links (
  id CHAR(36) NOT NULL,
  job_id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  allow_download BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at DATETIME(3) NULL,
  view_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_viewed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_links_token_hash (token_hash),
  KEY idx_share_links_user_job (user_id, job_id),
  CONSTRAINT fk_share_links_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_share_links_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS webhook_events (
  id CHAR(36) NOT NULL,
  provider ENUM('paypal') NOT NULL,
  provider_event_id VARCHAR(190) NOT NULL,
  event_type VARCHAR(120) NOT NULL,
  status ENUM('received', 'verified', 'processed', 'ignored', 'failed') NOT NULL DEFAULT 'received',
  payload JSON NOT NULL,
  error_message TEXT NULL,
  received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  processed_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_webhook_events_provider_event (provider, provider_event_id),
  KEY idx_webhook_events_status_received (status, received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS referrals (
  id CHAR(36) NOT NULL,
  referrer_user_id CHAR(36) NOT NULL,
  referred_user_id CHAR(36) NULL,
  code VARCHAR(32) NOT NULL,
  status ENUM('created', 'qualified', 'rewarded', 'cancelled') NOT NULL DEFAULT 'created',
  referrer_reward_credits INT UNSIGNED NOT NULL DEFAULT 10,
  referred_reward_credits INT UNSIGNED NOT NULL DEFAULT 10,
  qualified_at DATETIME(3) NULL,
  rewarded_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_referrals_code (code),
  UNIQUE KEY uq_referrals_referred_user (referred_user_id),
  KEY idx_referrals_referrer_status (referrer_user_id, status),
  CONSTRAINT fk_referrals_referrer FOREIGN KEY (referrer_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_referrals_referred FOREIGN KEY (referred_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS email_outbox (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NULL,
  template VARCHAR(80) NOT NULL,
  recipient VARCHAR(320) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  payload JSON NOT NULL,
  status ENUM('pending', 'sending', 'sent', 'failed') NOT NULL DEFAULT 'pending',
  attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  available_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  lease_owner VARCHAR(120) NULL,
  lease_expires_at DATETIME(3) NULL,
  last_error TEXT NULL,
  sent_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_email_outbox_claim (status, available_at, lease_expires_at),
  CONSTRAINT fk_email_outbox_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  actor_user_id CHAR(36) NULL,
  target_user_id CHAR(36) NULL,
  action VARCHAR(100) NOT NULL,
  resource_type VARCHAR(60) NULL,
  resource_id VARCHAR(80) NULL,
  request_id CHAR(36) NULL,
  ip_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  user_agent_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  outcome ENUM('success', 'denied', 'failure') NOT NULL,
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_audit_logs_actor_created (actor_user_id, created_at),
  KEY idx_audit_logs_target_created (target_user_id, created_at),
  KEY idx_audit_logs_action_created (action, created_at),
  CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_audit_logs_target FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
